server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:h2:mem:dev_db
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
